#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# we read a json stdin {"vars1":true, "var2":"foo", "vars3": 3} and we writ it to .config/state/environment
# Upper case to set environment variable and minor case to read from stdin

SURREALDB_NAME = data.get("SURREALDB_NAME", "root")
SURREALDB_PASSWORD = data.get("SURREAL_PASSWORD", "root")

agent.write_envfile("database.env", {
    "SURREALDB_NAME" : SURREALDB_NAME,
    "SURREALDB_PASSWORD": SURREALDB_PASSWORD
})

agent.set_env("SURREALDB_PASSWORD", SURREALDB_PASSWORD)
agent.set_env("SURREALDB_NAME", SURREALDB_NAME)

agent.dump_env()

