#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request['environment']

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "instance" : os.environ['MODULE_ID'],
    "url" : f'http://127.0.0.1:{os.environ['TCP_PORT']}',
    "lets_encrypt": renv["TRAEFIK_LETS_ENCRYPT"] == True,
    "host": renv["TRAEFIK_HOST"],
    "http2https": renv["TRAEFIK_HTTP2HTTPS"] == True,
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
